// <auto-generated />
using System;
using HOT4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOT4.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    partial class AppointmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOT4.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppTime")
                        .HasColumnType("time");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppTime = new TimeSpan(0, 15, 0, 0, 0),
                            CustomerId = 5,
                            PhoneNumber = "314-987-6543",
                            Username = "SandySue"
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppTime = new TimeSpan(0, 14, 0, 0, 0),
                            CustomerId = 2,
                            PhoneNumber = "314-299-0321",
                            Username = "JackieC999"
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppDate = new DateTime(2026, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppTime = new TimeSpan(0, 13, 0, 0, 0),
                            CustomerId = 3,
                            PhoneNumber = "618-407-6555",
                            Username = "DarylD4321"
                        },
                        new
                        {
                            AppointmentId = 4,
                            AppDate = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppTime = new TimeSpan(0, 17, 0, 0, 0),
                            CustomerId = 1,
                            PhoneNumber = "314-495-7733",
                            Username = "ThomasRoad123"
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppTime = new TimeSpan(0, 14, 0, 0, 0),
                            CustomerId = 5,
                            PhoneNumber = "314-987-6543",
                            Username = "SandySue"
                        },
                        new
                        {
                            AppointmentId = 6,
                            AppDate = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppTime = new TimeSpan(0, 16, 0, 0, 0),
                            CustomerId = 4,
                            PhoneNumber = "636-333-3210",
                            Username = "FrancisDay1"
                        });
                });

            modelBuilder.Entity("HOT4.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            PhoneNumber = "314-495-7733",
                            Username = "ThomasRoad123"
                        },
                        new
                        {
                            CustomerId = 2,
                            PhoneNumber = "314-299-0321",
                            Username = "JackieC999"
                        },
                        new
                        {
                            CustomerId = 3,
                            PhoneNumber = "618-407-6555",
                            Username = "DarylD4321"
                        },
                        new
                        {
                            CustomerId = 4,
                            PhoneNumber = "636-333-3210",
                            Username = "FrancisDay1"
                        },
                        new
                        {
                            CustomerId = 5,
                            PhoneNumber = "314-987-6543",
                            Username = "SandySue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
