// <auto-generated />
using System;
using HOT3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOT3.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOT3.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DepartmentName = "Men's"
                        },
                        new
                        {
                            CategoryId = 2,
                            DepartmentName = "Women's"
                        });
                });

            modelBuilder.Entity("HOT3.Models.Hoodie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoodieId")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Hoodies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Urban Threads",
                            CategoryId = 1,
                            Color = "Gray",
                            Description = "A classic hoodie for everyday wear.",
                            HoodieId = 0,
                            ImageFileName = "mens-classic-hoodie.jpg",
                            Material = "Cotton",
                            Name = "Classic Hoodie",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Cozy Core",
                            CategoryId = 2,
                            Color = "Creamed Coffee",
                            Description = "Cozy, oversized silhouette with exaggerated balloon sleeve.",
                            HoodieId = 0,
                            ImageFileName = "balloon-sleeve.jpg",
                            Material = "Cotton and polyester blend",
                            Name = "Oversized Balloon Sleeved Hoodie",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Everyday Essentials",
                            CategoryId = 1,
                            Color = "French vanilla",
                            Description = "A perfectly cozy hoodie with a boxy cut.",
                            HoodieId = 0,
                            ImageFileName = "classic-hoodie.jpg",
                            Material = "Cotton",
                            Name = "Classic Hoodie with a Boxy cut",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Cozy Core",
                            CategoryId = 2,
                            Color = "Destressed Black",
                            Description = "A unique hoodie full of vintage character. A true lived in feeling.",
                            HoodieId = 0,
                            ImageFileName = "destroyed-hoodie2.jpg",
                            Material = "Cotton",
                            Name = "Destroyed Hoodie",
                            Price = 54.99m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Urban Threads",
                            CategoryId = 1,
                            Color = "Gray",
                            Description = "A warm fleece hoodie for colder days. Or a curl up on the couch hoodie to keep you warm and comfy,",
                            HoodieId = 0,
                            ImageFileName = "fleece-lined-hoodie.jpg",
                            Material = "Cotten and Fleece",
                            Name = "Fleece Lined Hoodie",
                            Price = 64.99m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Urban Threads",
                            CategoryId = 1,
                            Color = "Washed Black",
                            Description = "Like your favorite hoodie you've had for years and always grab first.",
                            HoodieId = 0,
                            ImageFileName = "faded-hoodie.jpg",
                            Material = "Cotton",
                            Name = "Washed/Faded Hoodie",
                            Price = 44.99m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Vintage Vibes",
                            CategoryId = 2,
                            Color = "Multi flower",
                            Description = "A trendy oversized hoodie with a beautiful boho design.",
                            HoodieId = 0,
                            ImageFileName = "flower-hoodie.jpg",
                            Material = "Cotton Blend",
                            Name = "Oversized Flower Hoodie",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Urban Threads",
                            CategoryId = 1,
                            Color = "Caramel Latte",
                            Description = "A hoodie made from sustainable materials. Designed with a cropped and boxy fit to hit you at just the perfect place. ",
                            HoodieId = 0,
                            ImageFileName = "mens-boxy-cropped.jpg",
                            Material = "Organic Cotton and recycled polyester",
                            Name = "Boxy-Cropped Hoodie",
                            Price = 74.99m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Cozy Core",
                            CategoryId = 2,
                            Color = "Lavender bouqet",
                            Description = "A hoodie with balloon sleeves, optional side splits, soft french terry lining. Oversized fit.",
                            HoodieId = 0,
                            ImageFileName = "Oversized-hoodie.jpg",
                            Material = "Cotten",
                            Name = "Plus size Hoodie",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Everyday Essentials",
                            CategoryId = 2,
                            Color = "Mustard Olive",
                            Description = "A hoodie with a vintage look and feel. Extra cozy. Wear on a walk, on the couch, or the grocery store.",
                            HoodieId = 0,
                            ImageFileName = "womens-cotton-hoodie.jpg",
                            Material = "Cotton and Polyester",
                            Name = "Vintage Hoodie",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Vintage Vibes",
                            CategoryId = 2,
                            Color = "Red Goddess",
                            Description = "A stylish cropped hoodie. With the most amazing lived in fabric feel.",
                            HoodieId = 0,
                            ImageFileName = "womens-cropped.jpg",
                            Material = "Cotton",
                            Name = "Cropped Hoodie",
                            Price = 54.99m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Urban Threads",
                            CategoryId = 1,
                            Color = "Beige",
                            Description = "Brushed cotton and rayon for extra softness. A washed fabric with a zip up design.",
                            HoodieId = 0,
                            ImageFileName = "zip-up.jpg",
                            Material = "Cotton and rayon",
                            Name = "Brushed vintage zip up hoodie",
                            Price = 79.99m
                        });
                });

            modelBuilder.Entity("HOT3.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HoodieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoodieId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("HOT3.Models.Hoodie", b =>
                {
                    b.HasOne("HOT3.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HOT3.Models.Purchase", b =>
                {
                    b.HasOne("HOT3.Models.Hoodie", "Hoodie")
                        .WithMany()
                        .HasForeignKey("HoodieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoodie");
                });
#pragma warning restore 612, 618
        }
    }
}
