// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieProject.Models;

#nullable disable

namespace MovieProject.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20250908185755_initial2")]
    partial class initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieProject.Models.MovieModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Name = "Inception",
                            Rating = 8,
                            Year = 2010
                        },
                        new
                        {
                            MovieId = 2,
                            Name = "The Dark Knight",
                            Rating = 9,
                            Year = 2008
                        },
                        new
                        {
                            MovieId = 3,
                            Name = "Pulp Fiction",
                            Rating = 7,
                            Year = 1994
                        },
                        new
                        {
                            MovieId = 4,
                            Name = "The Shawshank Redemption",
                            Rating = 10,
                            Year = 1994
                        },
                        new
                        {
                            MovieId = 5,
                            Name = "The Godfather",
                            Rating = 9,
                            Year = 1972
                        },
                        new
                        {
                            MovieId = 6,
                            Name = "The Matrix",
                            Rating = 8,
                            Year = 1999
                        },
                        new
                        {
                            MovieId = 7,
                            Name = "Forrest Gump",
                            Rating = 8,
                            Year = 1994
                        },
                        new
                        {
                            MovieId = 8,
                            Name = "Fight Club",
                            Rating = 7,
                            Year = 1999
                        },
                        new
                        {
                            MovieId = 9,
                            Name = "Interstellar",
                            Rating = 8,
                            Year = 2014
                        },
                        new
                        {
                            MovieId = 10,
                            Name = "The Lord of the Rings: The Return of the King",
                            Rating = 9,
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
