// <auto-generated />
using GearheadAutoParts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GearheadAutoParts.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20250919043437_CategoryTB")]
    partial class CategoryTB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GearheadAutoParts.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Ignition System"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Braking System"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Suspension System"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Electrical System"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Exhaust System"
                        });
                });

            modelBuilder.Entity("GearheadAutoParts.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescLong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductQty")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ProductDescLong = "This spark plug is designed to provide a strong and consistent spark, ensuring efficient combustion and improved engine performance. It features a durable construction and is suitable for a wide range of vehicles.",
                            ProductDescShort = "High-performance spark plug for optimal ignition.",
                            ProductImage = "",
                            ProductName = "Spark Plug",
                            ProductPrice = 14.99m,
                            ProductQty = 150m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            ProductDescLong = "These brake pads are made from high-quality materials to ensure long-lasting performance and safety. They provide excellent friction and heat resistance, making them ideal for both everyday driving and high-performance applications.",
                            ProductDescShort = "Durable brake pads for reliable stopping power.",
                            ProductImage = "",
                            ProductName = "Brake Pads",
                            ProductPrice = 49.99m,
                            ProductQty = 80m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            ProductDescLong = "This shock absorber is engineered to absorb road vibrations and impacts, providing a comfortable and stable driving experience. It features advanced damping technology and is compatible with various vehicle models.",
                            ProductDescShort = "Premium shock absorber for a smooth ride.",
                            ProductImage = "",
                            ProductName = "Shock Absorber",
                            ProductPrice = 89.99m,
                            ProductQty = 60m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            ProductDescLong = "This alternator is designed to efficiently convert mechanical energy into electrical energy, ensuring a steady power supply to your vehicle's electrical systems. It features a robust design and is built to last.",
                            ProductDescShort = "Reliable alternator for consistent power supply.",
                            ProductImage = "",
                            ProductName = "Alternator",
                            ProductPrice = 199.99m,
                            ProductQty = 40m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            ProductDescLong = "This exhaust muffler is designed to reduce engine noise while maintaining optimal exhaust flow. It features a durable construction and is suitable for a variety of vehicle types, enhancing both performance and sound quality.",
                            ProductDescShort = "High-quality exhaust muffler for noise reduction.",
                            ProductImage = "",
                            ProductName = "Exhaust Muffler",
                            ProductPrice = 129.99m,
                            ProductQty = 70m
                        });
                });

            modelBuilder.Entity("GearheadAutoParts.Models.Product", b =>
                {
                    b.HasOne("GearheadAutoParts.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GearheadAutoParts.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
