// <auto-generated />
using GearheadAutoParts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GearheadAutoParts.Migrations
{
    [DbContext(typeof(SalesContext))]
    partial class SalesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GearheadAutoParts.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Ignition System"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Braking System"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Suspension System"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Electrical System"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Exhaust System"
                        });
                });

            modelBuilder.Entity("GearheadAutoParts.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescLong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Spark Plug",
                            ProductPrice = 14.99m,
                            ProductQty = 150
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Brake Pads",
                            ProductPrice = 49.99m,
                            ProductQty = 80
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Shock Absorber",
                            ProductPrice = 89.99m,
                            ProductQty = 60
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Alternator",
                            ProductPrice = 199.99m,
                            ProductQty = 40
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Exhaust Muffler",
                            ProductPrice = 129.99m,
                            ProductQty = 70
                        });
                });

            modelBuilder.Entity("GearheadAutoParts.Models.Product", b =>
                {
                    b.HasOne("GearheadAutoParts.Models.Category", "Category")
                        .WithOne("Product")
                        .HasForeignKey("GearheadAutoParts.Models.Product", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GearheadAutoParts.Models.Category", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
