// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripLog.Models;

#nullable disable

namespace TripLog.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20251012051710_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripLog.Models.Trip", b =>
                {
                    b.Property<int>("TripLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripLogId"));

                    b.Property<string>("Accommodation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccommodationEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccommodationPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("TripLogId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripLogId = 1,
                            Accommodation = "Royal Kona Resort",
                            AccommodationEmail = "Royal_Kona@gmail.com",
                            AccommodationPhone = "808-555-1234",
                            Activity1 = "See the Thurston Lava Tube",
                            Activity2 = "Snorkeling at Kealakekua Bay",
                            Activity3 = "Visit the Pu'uhonua o Honaunau National Historical Park",
                            Destination = "Hawaii",
                            EndDate = new DateOnly(2023, 1, 21),
                            StartDate = new DateOnly(2023, 1, 15)
                        },
                        new
                        {
                            TripLogId = 2,
                            Accommodation = "Lorelei Bed & Breakfast",
                            AccommodationEmail = "Lorelei_B&B_tripinfo.com",
                            AccommodationPhone = "503-555-5678",
                            Activity1 = "Japanese Garden",
                            Activity2 = "Portland Science Museum",
                            Activity3 = "Powell City of Books ",
                            Destination = "Portland Oregon",
                            EndDate = new DateOnly(2023, 1, 21),
                            StartDate = new DateOnly(2023, 2, 20)
                        },
                        new
                        {
                            TripLogId = 3,
                            Accommodation = "Holiday Inn",
                            AccommodationEmail = "Holiday-InnBESTNIGHTSLEEP@info.org",
                            AccommodationPhone = "941-555-9876",
                            Activity1 = "Beach day",
                            Activity2 = "Swimming with dolphins",
                            Activity3 = "Disney World",
                            Destination = " Sarasota Florida",
                            EndDate = new DateOnly(2027, 4, 21),
                            StartDate = new DateOnly(2027, 3, 25)
                        },
                        new
                        {
                            TripLogId = 4,
                            Accommodation = "Lodge of the Ozarks",
                            AccommodationEmail = "The_Lodge@ozarks.com",
                            AccommodationPhone = "417-555-2468",
                            Activity1 = "Silver Dollar City",
                            Activity2 = "Christmas Lights",
                            Activity3 = "Castle Rock Indoor WaterPark",
                            Destination = "Branson Missouri",
                            EndDate = new DateOnly(2026, 12, 30),
                            StartDate = new DateOnly(2026, 12, 16)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
