// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShop.Models;

#nullable disable

namespace MyShop.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyShop.Models.Bicycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bicycles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Trek",
                            Color = "Black",
                            ImageFileName = "favicon.ico",
                            Model = "FX 1 Gen 4",
                            Price = 699.99m,
                            Type = "Hybrid",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Giant",
                            Color = "Red",
                            ImageFileName = "giant-escape-3.jpg",
                            Model = "TCR Advanced Pro 1 Disc",
                            Price = 3500.00m,
                            Type = "Road",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Specialized",
                            Color = "Navy Blue",
                            ImageFileName = "specialized-rockhopper.jpg",
                            Model = "Rockhopper Expert 29",
                            Price = 1100.00m,
                            Type = "Mountain",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Cannondale",
                            Color = "Slate Gray",
                            ImageFileName = "cannondale-synapse.jpg",
                            Model = "Synapse Carbon 105",
                            Price = 2500.00m,
                            Type = "Road",
                            Year = 2024
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Schwinn",
                            Color = "Baby Blue",
                            ImageFileName = "schwinn-streamdale.jpg",
                            Model = "Streamdale 7 Speed Bike",
                            Price = 350.00m,
                            Type = "Road",
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Giant",
                            Color = "Red",
                            ImageFileName = "giant-escape-3.jpg",
                            Model = "Escape 3",
                            Price = 1500.00m,
                            Type = "Speed",
                            Year = 2025
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Specialized",
                            Color = "Copper",
                            ImageFileName = "specialized-turbo-levo-4.jpg",
                            Model = "S-Works Turbo Levo 4",
                            Price = 15399.99m,
                            Type = "Electric",
                            Year = 2025
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
