using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace NovelNook.Migrations.SeedData
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ExploreCards",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Title = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Author = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Image = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LinkUrl = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ExploreCards", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "ExploreCards",
                columns: new[] { "Id", "Author", "Description", "Image", "LinkUrl", "Title" },
                values: new object[,]
                {
                    { 1, "M.L. Wang", "Magic has made the city of Tiran an industrial utopia, but magic has a cost. A dark academia brimming with mystery, tradegy, bravery, and damning echoes of the past. Through their fractious relationship, mage and outsider uncover an ancient secret that could change the course of magic forever—if it doesn’t get them killed first. Sciona has defined her life by the pursuit of truth, but how much is one truth worth with the fate of civilization in the balance?", "/images/Blood-over-bright-haven.jpg", "https://www.amazon.com/dp/B0CVLFJMV2/?bestFormat=true&k=blood%20over%20bright%20haven&ref_=nb_sb_ss_w_scx-ent-pd-bk-d_k0_1_10_de&crid=1XVACO1WQC5QV&sprefix=blood%20%20over", "Blood Over Bright Haven" },
                    { 2, "John Paul Mueller, Luca Massaron, Stephanie Diamond", "A comprehensive guide for non-technical users. Artificial intelligence (AI) is the science of creating computer systems that can perform tasks normally requiring human intelligence, such as learning, reasoning, and problem-solving. ", "/images/Ai-Dummies.jpg", "https://www.amazon.com/Artificial-Intelligence-Dummies-John-Mueller-ebook/dp/B0DK8MXGVY/ref=sr_1_2?crid=398YM8TX5WG2X&dib=eyJ2IjoiMSJ9.O1MzbnF2WLxv7V74eaqHLMv2xSdWdVHIS_p5LFuqXTqFaE4mQNBTkzRVDUeJ-5jgRR9YNGQ-5UQuDMnnLHDcqcT9KdGfhEIHNvw_vzIyTDOAD7q8Jkc5QOo9vPXJfOxLXPpJpf8yQ7YqC0jsXpbQxzCE4cbXmKRZxw7H-l6fzXFGePIUNkxAQuZnYI8KUeCuoxBMWeNpzUaaUEXb2KoLEff35KYjJkR3vRA5BH70C-Y.oFTZLJkPu8EcKrYWzWtbogzuuhYR9rcs-ue8RjyhYFw&dib_tag=se&keywords=ai+for+dummies+2025&qid=1758747855&s=digital-text&sprefix=Ai+for+%2Cdigital-text%2C131&sr=1-2", "Artificial Intelligence for Dummies" },
                    { 3, "Bell Hooks", "All About Love: New Visions, bell hooks argues that love is not simply a feeling but a conscious, intentional choice. Hooks's central thesis is that \"love is as love does\". She explains that modern society has fundamentally misunderstood love by treating it as a noun—a mystical, passive emotion—rather than a verb, which implies intentional action and will.", "/images/all-about-love.jpg", "", "All About Love" },
                    { 4, "Mary Delamater Joel Murach", "Learn to write your first apps using MVC (Model-View-Controller) pattern. This book gets you off to a fast start whether or not you have prior experience with server-side development.\r\nIt teaches you all the skills you need to develop bulletproof, database-driven web apps. That includes using endpoint routing, Razor views, model binding, data validation, dependency injection, Bootstrap for responsive design, EF (Entity Framework) Core for database handling, xUnit and Moq for unit testing, and Identity for authentication", "/images/ASPNet.jpg", "", "murach's ASP.NET Core MVC" },
                    { 5, "Shannon Lee", " \"Empty your mind, be formless, shapeless—like water,\" was popularized by martial arts legend and philosopher Bruce Lee. The phrase is a core tenet of his philosophy, urging practitioners to become adaptable and fluid, both in combat and in life. \"Empty your mind, be formless, shapeless—like water. You put water into a cup, it becomes the cup. You put water into a bottle, it becomes the bottle. You put it in a teapot, it becomes the teapot. Now, water can flow or it can crash. Be water, my friend.", "/images/Be-Water-My-Friend.jpg", "", "Be Water My Friend" },
                    { 6, "Tatsuki Fujimoto", "Chainsaw Man, Vol. 1 introduces readers to Denji, a poor young man struggling with debt and despair. After being killed in a job, he is revived by his pet devil, Pochita, and transforms into Chainsaw Man, a powerful being with chainsaw-like abilities. The story follows Denji's journey as he seeks redemption and fights against devils, embodying humanity's darkest fears. The volume explores themes of hope, love, and the struggle for a better life, showcasing Denji's transformation and the bond he forms with Pochita. Denji is a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous—Chainsaw Man!", "/images/Chainsaw-man.jpg", "", "Chainsaw Man Vol. 1" },
                    { 7, "E.B. White", "Charlotte's Web is a classic 1952 children's novel by E.B. White about the unlikely friendship between a pig named Wilbur and a wise barn spider named Charlotte, who saves his life by spinning words in her web that praise him, preventing him from becoming pork chops. ", "/images/Charlottes-web.jpg", "", "Charlotte's Web" },
                    { 8, "Marissa Meyer", "Cinder by Marissa Meyer is the first book in The Lunar Chronicles, a young adult science fiction series that retells classic fairy tales in a futuristic, post-war world. The story follows Cinder, a cyborg mechanic in futuristic New Beijing, who is a second-class citizen with a hidden, mysterious past. When her life becomes entangled with Prince Kai, she finds herself at the center of an interplanetary struggle and a fight for Earth's survival against the tyrannical Queen Levana of the Lunar colony", "/images/Cinder.jpg", "", "Cinder" },
                    { 9, "Ichiro Kishimi and Fumitake Koga", "Having the courage to be disliked\" means accepting that you may face disapproval or criticism because you are living authentically and according to your own values, rather than trying to please others or conform to their expectations. It is the freedom to act according to your own beliefs and principles, even if it leads to rejection, and is seen as a pathway to genuine freedom and self-confidence", "/images/courage-disliked.jpg", "", "The Courage to be Disliked" },
                    { 10, "V.E. Schwab", "A Darker Shade of Magic by V.E. Schwab is a fantasy novel about Kell, a rare magician called an Antari, who can travel between four parallel versions of London. He serves as an ambassador in the magical Red London but also works as a smuggler, leading to his accidental acquisition of a forbidden black stone from Black London. When an exchange goes wrong, Kell escapes to the non-magical Grey London, where he meets the cunning thief Lila Bard, and together they embark on a perilous adventure to save all the worlds from a greedy, magic-hungry force", "/images/Darker-shade-of-magic.jpg", "", "A Darker Shade of Magic" },
                    { 11, "Blake Crouch", "A Darker Shade of Magic by V.E. Schwab is a fantasy novel about Kell, a rare magician called an Antari, who can travel between four parallel versions of London. He serves as an ambassador in the magical Red London but also works as a smuggler, leading to his accidental acquisition of a forbidden black stone from Black London. When an exchange goes wrong, Kell escapes to the non-magical Grey London, where he meets the cunning thief Lila Bard, and together they embark on a perilous adventure to save all the worlds from a greedy, magic-hungry force", "/images/Dark-matter.jpg", "", "Dark Matter" },
                    { 12, "Daniel Goleman", "a groundbreaking book that argues emotional intelligence (EI), encompassing self-awareness, impulse control, persistence, empathy, and social skills, is a more significant determinant of success than IQ. Drawing on psychology and neuroscience, the book explains how EI, which can be nurtured and developed, influences relationships, career success, and overall well-being, offering a new understanding of intelligence and a compelling vision for personal and societal growth.  ", "/images/Emotional-intelligence.jpg", "", "Emotional Intelligence" },
                    { 13, "Jason Stanley", "In Erasing History, Yale professor of philosophy Jason Stanley exposes the true danger of the authoritarian right’s attacks on education, identifies their key tactics and funders, and traces their intellectual roots. He illustrates how fears of a fascist future have metastasized, from hypothetical threat to present reality. And with his “urgent, piercing, and altogether brilliant” (Johnathan M. Metzl, author of What We’ve Become) insight, he illustrates that hearts and minds are won in our schools and universities—places that democratic societies across the world are now ill-prepared to defend against the fascist assault currently underway", "/images/Ai-Dummies.jpg", "", "Erasing History" },
                    { 14, "Pierce Brown", "Golden Son is the second novel in Pierce Brown's Red Rising Saga and follows Darrow as he continues his mission to destroy the Gold ruling class from within by becoming a leader among them after transforming from a lowborn Red to a Gold. The story expands on the political intrigue, betrayal, and warfare of the first book, with Darrow navigating treacherous alliances, growing his power, and preparing for a full-scale rebellion against the oppressive Society. \r\n", "/images/Golden-son.jpg", "", "Golden Son" },
                    { 15, "Margeret Atwood", "The Handmaid's Tale by Margaret Atwood is a dystopian novel published in 1985. Set in the near-future Republic of Gilead (formerly the United States), it follows Offred, a Handmaid whose sole purpose is to bear children for the ruling class. After environmental disasters cause a drastic drop in the birth rate, the totalitarian, patriarchal regime strips women of their rights and assigns them to specific social classes", "/images/handmaid-tale.jpg", "", "The Handmaid's Tale" },
                    { 16, "Alicia Ortego", "Kindness Is My Superpower is a children's book by Alicia Ortego that teaches young readers about empathy and compassion through the story of a boy named Lucas, who learns to make kindness his superpower. The book illustrates how simple acts like saying \"please\" and \"thank you,\" sharing, helping others, and apologizing can significantly impact others and create a positive environment. Through a heartwarming narrative, children learn that kindness, though sometimes challenging, is a source of inner strength and a powerful way to connect with the world around them", "/images/Kindness-is-My-Superpower.jpg", "", "Kindness is my Superpower" },
                    { 17, "Marshall Loeb, Stephen Kindel", "Leadership For Dummies is a practical guide that aims to teach anyone how to become a more effective leader, regardless of their current position or experience. The book moves beyond theory to provide hands-on strategies and techniques for developing leadership skills, building strong teams, and inspiring trust in others", "/images/Leadership-Dummies.jpg", "", "Leadership for Dummies" },
                    { 18, "Anthony Doer", "All the Light We Cannot See is a Pulitzer Prize-winning novel by Anthony Doerr that tells the parallel stories of a blind French girl and a German orphan boy during World War II. Their paths converge in the besieged French town of Saint-Malo as both struggle to survive the devastation of the war. ", "/images/Light-we-cannot-see.jpg", "", "All the Light We Cannot See" },
                    { 19, "Adam Grant", "Originals: How Non-Conformists Move the World by Adam Grant is a book that explores how to champion new and novel ideas, identify good ideas, speak up without being silenced, and build coalitions to bring disruptive concepts to life. Through stories and studies from various fields, Grant details the qualities of original people, provides tips for nurturing originality in children and leaders, and examines how fear and doubt can be managed on the path to innovation", "/images/Originals.jpg", "", "Originals" },
                    { 20, "Howards Zinn", "A People's History of the United States is a 1980 nonfiction book by historian Howard Zinn that tells the history of the country \"from the bottom up\". Zinn's work presents a different perspective than traditional narratives, focusing on the stories and struggles of marginalized groups rather than the powerful elites.", "/images/Peoples-history.jpg", "", "People's History of the United States" },
                    { 21, "Karin Slaughter", "Karin Slaughter's psychological thriller Pretty Girls centers on estranged sisters Claire and Lydia, who are forced to confront their family's devastating past when a new tragedy strikes. The book deals with themes of family trauma, secrets, and the nature of survival.", "/images/Pretty-girls.jpg", "", "Pretty Girls" },
                    { 22, "Mark Reed", " Python programming aimed at beginners. His books focus on a practical, hands-on approach to learning Python and often include real-world projects and exercises to help solidify understanding", "/images/Python.jpg", "", "Python Programming" },
                    { 23, "Pierce Brown", "Red Rising, written by Pierce Brown, is a science fiction novel that introduces a color-coded caste system where different classes of humanity occupy specific roles across the solar system. The story follows Darrow, a lowborn \"Red,\" who discovers the truth behind the oppressive society and embarks on a mission of vengeance and rebellion", "/images/Red-rising.jpg", "", "Red Rising" },
                    { 24, "Alex Michaelides", "The Silent Patient is a 2019 psychological thriller novel by Alex Michaelides about a psychotherapist who becomes obsessed with unraveling the mystery of his patient, a famous artist who has gone completely silent after murdering her husband", "/images/Silent-patient.jpg", "", "The Silent Patient" },
                    { 25, "Adam Grant", "Think Again: The Power of Knowing What You Don't Know by Adam Grant is about the importance of reexamining your beliefs and unlearning outdated knowledge to adapt and succeed in a rapidly changing world. Grant, an organizational psychologist, argues that what matters more than intelligence is \"mental flexibility\" and the willingness to question your own opinions.", "/images/Think-again.jpg", "", "Think Again" },
                    { 26, "V.E. Schwab", "V. E. Schwab's Vicious is a science fiction fantasy novel about two former college roommates, Victor Vale and Eli Ever, who turn into powerful arch-nemeses. After a shared research project goes horribly wrong, the two rivals develop extraordinary abilities and embark on a path of ambition, betrayal, and revenge. The story explores what happens when people gain superpowers in a world where there are no true heroes, only villains and anti-heroes with twisted motivations.", "/images/Vicious.jpg", "", "Vicious" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ExploreCards");
        }
    }
}
